### ISSUE TITLE
Conditional Sender (variables)

### ISSUE THREAD

**Issue by ondohotola** [Sematre/typst-letter-pro#18]
Hi,
I have tried to wrap sender into a conditional

```typst
#let originator = "doc"
#if orginator == "doc" {
   let sendername    = "Dr Eberhard W Lisse"
   let senderaddress1= "PO Box #####"
   let senderaddress2= "Bachbrecht 10007"
} else {
   let sendername    = "Eberhard W Lisse"
   let senderaddress1= "PO Box #####"
   let senderaddress2= "Bachbrecht 10007"
}
```

then something like

```tpyst
#show: letter-simple.with(
   format: "DIN-5008-B",
   sender: (
      name: sendername,
      address: [· #senderaddress1 · #senderaddress2],
   ),
...
```

tells me the `sendername` variable is not known.

Without the `if {}` it works.

**Comment by Sematre** [comment]
The problem here is that curly brackets (`{`, `}`) create a new scope and variables that are created inside this scope will be destroyed when leaving this scope. So this annotated code:

```typst
#let originator = "doc"
#if orginator == "doc" {
   // NEW SCOPE STARTS HERE
   let sendername    = "Dr Eberhard W Lisse"
   // NEW SCOPE ENDS HERE, THUS DESTROYING sendername
} else {
   // NEW SCOPE STARTS HERE
   let sendername    = "Eberhard W Lisse"
   // NEW SCOPE ENDS HERE, THUS DESTROYING sendername
}

// sendername DOES NOT EXIST HERE
```

To fix your code, you need to separate the variable definition from the variable declaration.
```typst
// Move declaration up here
#let sendername
#let senderaddress1
#let senderaddress2

#let originator = "doc"
#if originator == "doc" {
   sendername    = "Dr Eberhard W Lisse"
   senderaddress1= "PO Box #####"
   senderaddress2= "Bachbrecht 10007"
} else {
   sendername    = "Eberhard W Lisse"
   senderaddress1= "PO Box #####"
   senderaddress2= "Bachbrecht 10007"
}
```

Also: Keep in mind that this a general Typst question, that is not specific to this library, and should rather be asked on the Typst Forum or Discord. [See here.](https://typst.app/docs/community/)

**Comment by ondohotola** [comment]
Thank you, very much.

Also, keep in mind that I am an elderly (retired) Gynecologist dabbling a little in Perl, but struggling with many Typst concepts :-)-O
