### ISSUE TITLE
Position/margin of information-box

### ISSUE THREAD

**Issue by kleinph** [Sematre/typst-letter-pro#8]
I am not sure if this is intended, but the information-box is not aligned with the sender box when right aligned.

![grafik](https://github.com/Sematre/typst-letter-pro/assets/566413/cab46f81-cc06-4b32-b53c-bd69356d1ac9)

````typst
information-box: [
    #set align(end)

    Kunden UID-Nr. \
    ATU12345678

    Rechnung Nr. \
    2023-001
 ],
````

Thanks!

**Comment by Sematre** [comment]
Yes, this is intentional. DIN 5008 specifies the information box to have a with of 75mm max.

[This image from Wikipedia](https://de.wikipedia.org/wiki/DIN_5008#/media/Datei:DIN_5008,_Form_A.svg) explains it quite well:
![DIN_5008,_Form_A](https://github.com/Sematre/typst-letter-pro/assets/7118368/064b9a35-b76f-488a-a244-55b1b2ced9f0)

I recommend adding 10mm extra padding when right aligning:
```typst
#show: letter-simple.with(
  // [...]
  information-box: pad(right: 10mm)[
    #set align(end)
    
    Kunden UID-Nr. \
    ATU12345678
    
    Rechnung Nr. \
    2023-001
  ],
  // [...]
)
```

**Comment by kleinph** [comment]
Thank you very much, this works. I tried `pad` before, but used it the wrong way (with `#set`).
